server:
  port: 8081
spring:
  application:
    name: bpos-product
  cloud:
    alibaba:
      seata:
        tx-service-group: bpos_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?tinyInt1isBit=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: chusen

  jpa:
    properties:
      hibernate:
        # 批量插入、更新
        batch_size: 300
        batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
        hbm2ddl:
        auto: validate
        use-sql-comments: true
    show-sql: true

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace